name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}

      - name: Release
        id: release
        uses: ridedott/release-me-action@master
        with:
          disable-changelog: true
          node-module: false
          release-branches: '["main"]'

      - name: Output
        run: |
          echo released version: ${{ steps.release.outputs.version }}, type: ${{ steps.release.outputs.level }}

  build_and_push:
    needs: release
    runs-on: ubuntu-latest

    permissions:
          contents: read
          packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: murzbul/face-client-api

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.release.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
